openapi: 3.0.3
info:
    title: Grocery list backend - OpenAPI 3.0
    description: |-
        This is a Grocery list backend server based on the OpenAPI 3.0 specification.
        Some useful links:
        - [Grocery list backend repository](https://github.com/LongWyrsch/Grocery-list_backend)

    termsOfService: http://localhost:3001/tos
    contact:
        email: long.nqw@gmail.com
    version: 1.0.0
servers:
    - url: http://localhost:3000
tags:
    - name: auth
      description: Creating and accessing accounts
    - name: recipes
      description: Access to recipes
    - name: lists
      description: Acces to lists
    - name: users
      description: Access user details
paths:
    /auth/google:
        get:
            tags:
                - auth
            summary: 'Step 1 in Google OAuth 2.0 authentication'
            description: 'Redirect user to Google OAuth 2.0 page'
            operationId: googleAuthPt1
            responses:
                '302':
                    description: 'Redirected to Google OAuth 2.0'
    /auth/google/callback:
        get:
            tags:
                - auth
            summary: 'Step 2 in Google OAuth 2.0 authentication'
            description: Google redirects user to app
            operationId: googleAuthPt2
            responses:
                '200':
                    description: 'User successfully authenticated'
    /auth/local/login:
        post:
            tags:
                - auth
            summary: Local login
            description: Login with email and password
            operationId: localLogin
            requestBody:
                description: User email and password
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: 'example@domain.com'
                                password:
                                    type: string
                                    format: password
                                    example: 123password
                required: true
            responses:
                '200':
                    description: 'User successfully authenticated'
    /auth/local/register:
        post:
            tags:
                - auth
            summary: Local register
            description: Register with email and password
            operationId: localRegister
            requestBody:
                description: User email and password
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: 'example@domain.com'
                                password:
                                    type: string
                                    format: password
                                    example: 123password
                required: true
            responses:
                '200':
                    description: 'User successfully authenticated'
    /users:
        put:
            tags:
                - users
            summary: Update user
            description: Update user
            operationId: updateUser
            requestBody:
                $ref: '#/components/requestBodies/User'
            responses:
                '200':
                    description: User successfully updated
                '502':
                    description: 'Failed to update data into database'
        delete:
            tags:
                - users
            summary: Delete user
            description: Delete user
            operationId: deleteUser
            parameters:
                - name: uuid
                  in: query
                  description: User uuid
                  required: false
                  schema:
                      type: string
                      format: uuid
                      example: '123e4567-e89b-12d3-a456-426614174000'
            responses:
                '200':
                    description: Recipe ingredient successfully delete
                '502':
                    description: 'Failed to delete data from database'
    /avatars:
        put:
            tags:
                - users
            summary: Update avatar
            description: Update avatar
            operationId: updateAvatar
            requestBody:
                $ref: '#/components/requestBodies/Avatar'
            responses:
                '200':
                    description: Avatar successfully updated
                '502':
                    description: 'Failed to update data into database'
    /recipes:
        get:
            tags:
                - recipes
            summary: Get all recipes
            description: Get all recipes
            operationId: allRecipies
            responses:
                '200':
                    description: Recipes fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/RecipeIngredient'
                '204':
                    description: 'User has no recipes'
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/RecipeIngredient'
                '502':
                    description: 'Failed to retrieve data from database'
        post:
            tags:
                - recipes
            summary: Create new recipe
            description: Create new recipe
            operationId: createRecipe
            requestBody:
                $ref: '#/components/requestBodies/Recipe'
            responses:
                '201':
                    description: New recipe successfully created
                '502':
                    description: 'Failed to insert data into database'
        put:
            tags:
                - recipes
            summary: Update recipe ingredient
            description: Update recipe ingredient
            operationId: updateRecipeIngredient
            requestBody:
                description: Update a recipe ingredient
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RecipeIngredient'
                required: true
            responses:
                '200':
                    description: Recipe ingredient successfully updated
                '502':
                    description: 'Failed to update data into database'
        delete:
            tags:
                - recipes
            summary: Delete recipe or recipe ingredient
            description: Delete recipe or recipe ingredient
            operationId: deleteRecipeIngredient
            parameters:
                - name: uuid
                  in: query
                  description: Recipe ingredient uuid to delete
                  required: false
                  schema:
                      type: string
                      format: uuid
                      example: '123e4567-e89b-12d3-a456-426614174000'
                - name: recipe
                  in: query
                  description: Recipe name to delete
                  required: false
                  schema:
                      type: string
                      example: 'Lasagna'
            responses:
                '200':
                    description: Recipe ingredient successfully delete
                '502':
                    description: 'Failed to delete data from database'
    /lists:
        get:
            tags:
                - lists
            summary: Get all lists
            description: Get all lists
            operationId: allLists
            responses:
                '200':
                    description: Lists fetched successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ListIngredient'
                '204':
                    description: 'User has no lists'
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ListIngredient'
                '502':
                    description: 'Failed to retrieve data from database'
        post:
            tags:
                - lists
            summary: Create new list
            description: Create new list
            operationId: createList
            requestBody:
                $ref: '#/components/requestBodies/List'
            responses:
                '201':
                    description: New list successfully created
                '502':
                    description: 'Failed to insert data into database'
        put:
            tags:
                - lists
            summary: Update list ingredient
            description: Update list ingredient
            operationId: updateListIngredient
            requestBody:
                description: Update a list ingredient
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ListIngredient'
                required: true
            responses:
                '200':
                    description: List ingredient successfully updated
                '502':
                    description: 'Failed to update data into database'
        delete:
            tags:
                - lists
            summary: Delete list or list ingredient
            description: Delete list or list ingredient
            operationId: deleteListIngredient
            parameters:
                - name: uuid
                  in: query
                  description: List ingredient uuid to delete
                  required: false
                  schema:
                      type: string
                      format: uuid
                      example: '123e4567-e89b-12d3-a456-426614174000'
                - name: list
                  in: query
                  description: List to delete
                  required: false
                  schema:
                      type: string
                      example: 'Italian'
            responses:
                '200':
                    description: List ingredient successfully delete
                '502':
                    description: 'Failed to delete data from database'
components:
    schemas:
        User:
            type: object
            properties:
                uuid:
                    type: string
                    format: uuid
                    example: '123e4567-e89b-12d3-a456-426614174000'
                email:
                    type: string
                    format: email
                    example: 'example@domain.com'
                hashedpassword:
                    type: string
                    format: password
                    example: '$2a$10$oRNpb2somlvHF3CFHQvJ4OGD5Bq18W2CkFGtrRh5KjD1VgQ/jBUna'
                role:
                    type: string
                    example: user
                language:
                    type: string
                    example: ENG
                darkmode:
                    type: boolean
                    example: false
                googleId:
                    type: string
                    example: '1234567890123456789'
                googleName:
                    type: string
                    example: John Smith
        RecipeIngredient:
            type: object
            properties:
                uuid:
                    type: string
                    format: uuid
                    example: '123e4567-e89b-12d3-a456-426614174000'
                user_uuid:
                    type: string
                    format: uuid
                    example: '123e4567-e89b-12d3-a456-426614174000'
                recipe:
                    type: string
                    example: Lasagna
                ingredient:
                    type: string
                    example: tomato sauce
                quantity:
                    type: number
                    example: 400
                unit:
                    type: string
                    example: ml
                section:
                    type: string
                    example: seasonings
                kCal:
                    type: number
                    example: 0
                index:
                    type: number
                    example: 1
        ListIngredient:
            type: object
            properties:
                uuid:
                    type: string
                    format: uuid
                    example: '123e4567-e89b-12d3-a456-426614174000'
                user_uuid:
                    type: string
                    format: uuid
                    example: '123e4567-e89b-12d3-a456-426614174000'
                title:
                    type: string
                    example: Italian
                checked:
                    type: boolean
                    example: false
                ingredient:
                    type: string
                    example: tomato sauce
                quantity:
                    type: number
                    example: 400
                unit:
                    type: string
                    example: ml
                section:
                    type: string
                    example: seasonings
                index:
                    type: number
                    example: 1
        Avatar:
            type: object
            properties:
                user_uuid:
                    type: string
                    format: uuid
                    example: '123e4567-e89b-12d3-a456-426614174000'
                variant:
                    type: string
                    example: marble
                colors:
                    type: array
                    items:
                        type: string
                        example: '#92A1C6'
    requestBodies:
        Recipe:
            description: Recipe ingredients that needs to be added to updated
            required: true
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/RecipeIngredient'
        List:
            description: List ingredients that needs to be added to updated
            required: true
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: '#/components/schemas/ListIngredient'
        Avatar:
            description: Avatar properties to update
            required: true
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Avatar'
        User:
            description: User properties to update
            required: true
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/User'
