POST http://localhost:3000/auth/local/signup HTTP/1.1
Origin: https://localhost:3001
Content-Type: application/json

{
    "email":"ssssdasfff",
    "password":"password",
    "theme":"light",
    "language":"en"
}

###

PUT http://localhost:3000/users HTTP/1.1
Origin: https://localhost:3001
Content-Type: application/json

{
    "email":"ssssdasfff",
    "password":"password",
    "theme":"light",
    "language":"en"
}
