Table "roles" {
  "role" text [pk]
}

Table "languages" {
  "language" text [pk]  
}


Table "units" {
  "unit" text [pk]
}

Table "sections" {
  "section" text [pk]
}

Table "users" {
  "uuid" uuid [pk]
  "email" text [unique, null]
  "hashedPassword" text [unique, null]
  "googleId" text [unique, null]
  "googleName" text [null]
  "role" text [not null, ref: > roles.role]
  "language" text [not null, ref: > languages.language]
  "darktheme" boolean [not null]
}

Table "avatars" {
  "user_uuid" uuid [pk, ref: <> users.uuid] 
  "variant" text [not null]
  "colors" varchar(6)[] [not null]
}

Table "recipes" {
  "uuid" uuid [pk]
  "user_uuid" uuid [not null, ref: > users.uuid]
  "recipe" text [not null]
  "ingredient" text [not null]
  "quantity" numeric [null]
  "unit" text [null]
  "section" text [not null, ref: > sections.section]
  "kCal" numeric [null]
  "index" numeric [not null]
}

Table "lists" {
  "uuid" uuid [pk]
  "title" text [not null]
  "checked" boolean [not null]
  "ingredient" text [not null]
  "quantity" numeric [null]
  "unit" text [null]
  "index" numeric [not null]
}

Table "list_recipe" {
  "list_title" text 
  "recipe" text 

  Indexes {
    (list_title, recipe) [pk]
  }
}